namespace KanzApi.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanzApi.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string CancelOrderNotAllowed
        {
            get
            {
                return ResourceManager.GetString("CancelOrderNotAllowed", resourceCulture);
            }
        }

        public static string DatabaseError
        {
            get
            {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }

        public static string DeliveryError
        {
            get
            {
                return ResourceManager.GetString("DeliveryError", resourceCulture);
            }
        }

        public static string DeliveryUnknown
        {
            get
            {
                return ResourceManager.GetString("DeliveryUnknown", resourceCulture);
            }
        }

        public static string EmptyCart
        {
            get
            {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }

        public static string EntityNotFound
        {
            get
            {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }

        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string ExchangeAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("ExchangeAlreadyExist", resourceCulture);
            }
        }

        public static string FileAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("FileAlreadyExist", resourceCulture);
            }
        }

        public static string Forbidden
        {
            get
            {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }

        public static string InvalidExchangeQuantity
        {
            get
            {
                return ResourceManager.GetString("InvalidExchangeQuantity", resourceCulture);
            }
        }

        public static string InvalidOtp
        {
            get
            {
                return ResourceManager.GetString("InvalidOtp", resourceCulture);
            }
        }

        public static string InvalidPassword
        {
            get
            {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        public static string InvalidPurchaseQuoteConfirmedQuantity
        {
            get
            {
                return ResourceManager.GetString("InvalidPurchaseQuoteConfirmedQuantity", resourceCulture);
            }
        }

        public static string InvalidRefundQuantity
        {
            get
            {
                return ResourceManager.GetString("InvalidRefundQuantity", resourceCulture);
            }
        }

        public static string InvalidStateChange
        {
            get
            {
                return ResourceManager.GetString("InvalidStateChange", resourceCulture);
            }
        }

        public static string InvalidToken
        {
            get
            {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }

        public static string MailError
        {
            get
            {
                return ResourceManager.GetString("MailError", resourceCulture);
            }
        }

        public static string MailUnknown
        {
            get
            {
                return ResourceManager.GetString("MailUnknown", resourceCulture);
            }
        }

        public static string OtpError
        {
            get
            {
                return ResourceManager.GetString("OtpError", resourceCulture);
            }
        }

        public static string OtpExpired
        {
            get
            {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }

        public static string OtpMaxAttempt
        {
            get
            {
                return ResourceManager.GetString("OtpMaxAttempt", resourceCulture);
            }
        }

        public static string OtpUnknown
        {
            get
            {
                return ResourceManager.GetString("OtpUnknown", resourceCulture);
            }
        }

        public static string PathNotFound
        {
            get
            {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }

        public static string PaymentError
        {
            get
            {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }

        public static string PaymentHashMismatch
        {
            get
            {
                return ResourceManager.GetString("PaymentHashMismatch", resourceCulture);
            }
        }

        public static string PaymentUnknown
        {
            get
            {
                return ResourceManager.GetString("PaymentUnknown", resourceCulture);
            }
        }

        public static string PrincipalNotAllowed
        {
            get
            {
                return ResourceManager.GetString("PrincipalNotAllowed", resourceCulture);
            }
        }

        public static string PrincipalTypeNotAllowed
        {
            get
            {
                return ResourceManager.GetString("PrincipalTypeNotAllowed", resourceCulture);
            }
        }

        public static string ProductMismatch
        {
            get
            {
                return ResourceManager.GetString("ProductMismatch", resourceCulture);
            }
        }

        public static string RecursiveParent
        {
            get
            {
                return ResourceManager.GetString("RecursiveParent", resourceCulture);
            }
        }

        public static string RefundAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("RefundAlreadyExist", resourceCulture);
            }
        }

        public static string ReviewSubmitted
        {
            get
            {
                return ResourceManager.GetString("ReviewSubmitted", resourceCulture);
            }
        }

        public static string SaleItemOutOfStock
        {
            get
            {
                return ResourceManager.GetString("SaleItemOutOfStock", resourceCulture);
            }
        }

        public static string SaleItemPriceMismatch
        {
            get
            {
                return ResourceManager.GetString("SaleItemPriceMismatch", resourceCulture);
            }
        }

        public static string StateNotAllowed
        {
            get
            {
                return ResourceManager.GetString("StateNotAllowed", resourceCulture);
            }
        }

        public static string TokenExpired
        {
            get
            {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }

        public static string Unauthorized
        {
            get
            {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }

        public static string UniqueConstraintViolation
        {
            get
            {
                return ResourceManager.GetString("UniqueConstraintViolation", resourceCulture);
            }
        }

        public static string Unknown
        {
            get
            {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        public static string UrlShortenerError
        {
            get
            {
                return ResourceManager.GetString("UrlShortenerError", resourceCulture);
            }
        }

        public static string UrlShortenerUnknown
        {
            get
            {
                return ResourceManager.GetString("UrlShortenerUnknown", resourceCulture);
            }
        }

        public static string UsernameAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("UsernameAlreadyExist", resourceCulture);
            }
        }

        public static string UsernameAndPasswordNotFound
        {
            get
            {
                return ResourceManager.GetString("UsernameAndPasswordNotFound", resourceCulture);
            }
        }

        public static string UserNotActive
        {
            get
            {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }

        public static string Validation
        {
            get
            {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
    }
}