namespace KanzApi.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanzApi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AccountApprovalNotificationMessage
        {
            get
            {
                return ResourceManager.GetString("AccountApprovalNotificationMessage", resourceCulture);
            }
        }

        public static string AccountApprovalNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("AccountApprovalNotificationTitle", resourceCulture);
            }
        }

        public static string AccountApprovedMailAction
        {
            get
            {
                return ResourceManager.GetString("AccountApprovedMailAction", resourceCulture);
            }
        }

        public static string AccountApprovedMailMessage
        {
            get
            {
                return ResourceManager.GetString("AccountApprovedMailMessage", resourceCulture);
            }
        }

        public static string AccountApprovedMailTitle
        {
            get
            {
                return ResourceManager.GetString("AccountApprovedMailTitle", resourceCulture);
            }
        }

        public static string AccountRejectedMailMessage
        {
            get
            {
                return ResourceManager.GetString("AccountRejectedMailMessage", resourceCulture);
            }
        }

        public static string AccountRejectedMailTitle
        {
            get
            {
                return ResourceManager.GetString("AccountRejectedMailTitle", resourceCulture);
            }
        }

        public static string OrderDeliveredMailMessage1
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredMailMessage1", resourceCulture);
            }
        }

        public static string OrderDeliveredMailMessage2
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredMailMessage2", resourceCulture);
            }
        }

        public static string OrderDeliveredMailMessage3
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredMailMessage3", resourceCulture);
            }
        }

        public static string OrderDeliveredMailMessage4
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredMailMessage4", resourceCulture);
            }
        }

        public static string OrderDeliveredMailTitle
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredMailTitle", resourceCulture);
            }
        }

        public static string OrderDeliveredNotificationMessage
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredNotificationMessage", resourceCulture);
            }
        }

        public static string OrderDeliveredNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("OrderDeliveredNotificationTitle", resourceCulture);
            }
        }

        public static string OrderOpenedMailAction
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailAction", resourceCulture);
            }
        }

        public static string OrderOpenedMailMessage1
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailMessage1", resourceCulture);
            }
        }

        public static string OrderOpenedMailMessage2
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailMessage2", resourceCulture);
            }
        }

        public static string OrderOpenedMailMessage3
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailMessage3", resourceCulture);
            }
        }

        public static string OrderOpenedMailMessage4
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailMessage4", resourceCulture);
            }
        }

        public static string OrderOpenedMailTitle
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedMailTitle", resourceCulture);
            }
        }

        public static string OrderOpenedNotificationMessage
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedNotificationMessage", resourceCulture);
            }
        }

        public static string OrderOpenedNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedNotificationTitle", resourceCulture);
            }
        }

        public static string OrderOpenedSms
        {
            get
            {
                return ResourceManager.GetString("OrderOpenedSms", resourceCulture);
            }
        }

        public static string OtpSms
        {
            get
            {
                return ResourceManager.GetString("OtpSms", resourceCulture);
            }
        }
    }
}