namespace KanzApi.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanzApi.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string DocumentFile
        {
            get
            {
                return ResourceManager.GetString("DocumentFile", resourceCulture);
            }
        }

        public static string EmailAddress
        {
            get
            {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        public static string FixedLength
        {
            get
            {
                return ResourceManager.GetString("FixedLength", resourceCulture);
            }
        }

        public static string FixedSize
        {
            get
            {
                return ResourceManager.GetString("FixedSize", resourceCulture);
            }
        }

        public static string ImageFile
        {
            get
            {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }

        public static string Max
        {
            get
            {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }

        public static string MaxLength
        {
            get
            {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }

        public static string MaxSize
        {
            get
            {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }

        public static string Min
        {
            get
            {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }

        public static string MinLength
        {
            get
            {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }

        public static string MinSize
        {
            get
            {
                return ResourceManager.GetString("MinSize", resourceCulture);
            }
        }

        public static string NotEmpty
        {
            get
            {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }

        public static string NotNull
        {
            get
            {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }

        public static string Numeric
        {
            get
            {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string Range
        {
            get
            {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }

        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}