name: Build and Deploy to Docker Container

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t kanzapi:latest .

      - name: Save Docker image to a file
        run: docker save -o kanzapi.tar kanzapi:latest

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          source: 'kanzapi.tar'
          target: '~/kanzapi.tar'

      - name: SSH to Azure VM and load Docker image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/kanzapi.tar
            docker run -d -p 80:80 kanzapi:latest
