name: Deploy .NET 8 Application to VM Docker Container

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .NET application
        run: dotnet publish -c Release -o out

      - name: Build Docker image
        run: docker build -t kanzapi:latest .

      - name: Save Docker image to file
        run: docker save kanzapi:latest | gzip > kanzapi.tar.gz

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Verify sshpass installation
        run: sshpass -V

      - name: Copy Docker image to VM
        env:
          VM_HOST: ${{ secrets.AZURE_VM_HOST }}
          VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          sshpass -p "${VM_PASSWORD}" scp -o StrictHostKeyChecking=no -P 22 kanzapi.tar.gz ${VM_USERNAME}@${VM_HOST}:~/kanzapi/image/kanzapi.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Verify sshpass installation
        run: sshpass -V

      - name: Load Docker image on VM and deploy
        env:
          VM_HOST: ${{ secrets.AZURE_VM_HOST }}
          VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          sshpass -p "${VM_PASSWORD}" ssh -o StrictHostKeyChecking=no -p 22 ${VM_USERNAME}@${VM_HOST} << 'EOF'
          gunzip -c ~/kanzapi/image/kanzapi.tar.gz | docker load
          docker stop kanzapi || true
          docker rm kanzapi || true
          docker run -d --name kanzapi -p 80:80 -v ~/kanzapi/secret/secrets.json:/kanzapi/secrets.json -e ASPNETCORE_ENVIRONMENT=Development kanzapi:latest
          EOF
