name: Deploy .NET 8 Application to VM Docker Container

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .NET application
        run: dotnet publish -c Release -o out

      - name: Build Docker image
        run: docker build -t kanzapi:latest .

      - name: Save Docker image to file
        run: docker save kanzapi:latest | gzip > image.tar.gz

      - name: Copy Docker image to VM
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          source: image.tar.gz
          target: ~/image.tar.gz

      - name: Load Docker image on VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            gunzip -c ~/image.tar.gz | docker load
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:80 kanzapi:latest
