name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t kanzapi:latest .

      - name: Save Docker image to a file
        run: docker save -o kanzapi.tar kanzapi:latest

      - name: Verify Docker image file
        run: ls -lh kanzapi.tar

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ~/.ssh/id_rsa
          port: 22
          source: 'kanzapi.tar'
          target: '~/kanzapi.tar'
          command_timeout: 10m
          timeout: 30s

      - name: Verify transferred file on Azure VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ~/.ssh/id_rsa
          port: 22
          script: ls -lh ~/kanzapi.tar

      - name: Load Docker image and run container on Azure VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ~/.ssh/id_rsa
          port: 22
          script: |
            docker load -i ~/kanzapi.tar
            docker run -d -p 80:80 kanzapi:latest
